name: todo-mern

services:
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/todo
      - JWT_SECRET=digital
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo
    restart: always
  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:5000/api
        - BACKEND_URL=http://backend:5000/api
        - NEXT_PUBLIC_ENV=stg
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api
      - BACKEND_URL=http://backend:5000/api
      - NEXT_PUBLIC_ENV=stg
    volumes:
      - /app/node_modules
    depends_on:
      - backend

volumes:
  mongo-data:
